os:
  - linux
language: node_js
node_js:
    - node
sudo: true
install:
    - npm install
    - export DISPLAY=':99.0'
    - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
script:
    - npm test
addons:
    apt:
        packages:
            - xvfb
cache:
  directories:
    - node_modules