os:
  - linux 

sudo: required

language: node_js

node_js:
  - "10.8.0"

branches:
  only:
    - master

script: ./script/travis-build.sh

node --version
npm --version

npm install
npm test

cache:
  directories:
    - node_modules