os:
  - linux

sudo: required

language: node_js

node_js:
  - "10.8.0"

branches:
  only:
    - master

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then \
  - export DISPLAY=:99.0 \
  - sh -e /etc/init.d/xvfb start \
  - sleep 3 \
  - fi 

node --version
npm --version

npm install
npm test

cache:
  directories:
    - node_modules