os:
  - linux

language: node_js

node_js:
  - "10.8.0"

branches:
  only:
    - master

script:
  - node --version
  - npm --version
  - npm install
  - xvfb-run npm test


cache:
  directories:
    - node_modules