os:
  - linux
language: node_js
node_js:
    - node
sudo: true

before_script:
  - export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start

script:
  - node --version
  - npm --version
  - npm install
  - npm test

addons:
    apt:
        packages:
            - xvfb
cache:
  directories:
    - node_modules