build: off

os: unstable

platform:
  - x86
  - x64

branches:
  only:
    - master

skip_tags: true

environment:
  nodejs_version: "10.8.0"

cache:
  - node_modules -> package.json

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version
  - npm --version
  - npm test
